server:
  port: 9000

# Swagger UI Configuration
# https://www.baeldung.com/spring-rest-openapi-documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v2_basic_concept
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update